### ISSUE TITLE
Implement some missing members

### ISSUE THREAD

**Issue by teto** [Cocophotos/vim-ycm-latex-semantic-completer#2]
Hi,

I came across this completer when searching to solve:
https://github.com/lervag/vimtex/issues/564#issuecomment-248413115
Do you intend to implement such a feature ? (i.e., "GoTo" support) I would find it very practical !

Same question for the command `:YcmShowDetailedDiagnostic`, to know which libraries are parsed for instance, for now it returns:
`NoDiagnosticSupport: YCM has no diagnostics support for this filetype; refer to Syntastic docs if using Syntastic.`

**Comment by Cocophotos** [comment]
Hi,

Thanks for the pull request and for the issue. I'll look into it, but it won't be before end of November. I have a lot on my plate right now :-)

Best,

## 

Corentin

**Comment by teto** [comment]
I tried to have a look at it but the completer seems inefficient, loading all the files everytime it searches for an entry. Also not sure bibtexparser can get the line from the entry, which means one would need to grep the file. Too much work for me too  right now

**Comment by Cocophotos** [comment]
Hi,

I've implemented some kind of memoization, so that the files are not re-read each time a completion request is fired. It will be more efficient that way. Note though that I've used this completer on a daily basis for 6 months when I was writing my PhD thesis and quite frankly, the performance were good.

I look into the GoTo definition command when I have a chance.

Best,

## 

Corentin

**Comment by teto** [comment]
I have both a very fast (SSD) and a slow computer (HDD). On the slow computer, the first completion request times out and then it works fine.
I started writing a GoTo implementation but haven't pushed it yet and it didn't work. I dunno how to log ycm messages yet to debug it :'( It should work, I just miss the line number from bibtexparser. 
I've started writing my PhD thesis , hence my interest in this :)
(In a not so distant future, with neovim/nyaovim etc... it should be possible to display a popup for the tex citation instead of GoTo but we are not here yet )

**Comment by Cocophotos** [comment]
Can you tell me if it's now better on your slow computer, please?

Regarding the debugging of YCM, I've used YcmDebugInfo to get my hand on the stdout.log and on the stderr.log and by reading the stderr.log, you know what is going on with your Python code. It's not very handy but at least it works.

You can make a pull requests and I look into the code. I've started to search for another bibtex parser and I've found this one : https://github.com/ptigas/bibpy/tree/master/bibpy . It has a self.line which we can expose to have access to the line number. Regarding the column number for the bibtex file, we can just put 0 for the start of the line. It should work just fine.

Good luck with writing your PhD thesis (on what are you working BTW?)

Best,

## 

Corentin

**Comment by teto** [comment]
Here it is (haven't rebased yet), I think I should check what's the request_data 
https://github.com/teto/vim-ycm-latex-semantic-completer/tree/add_goto

Merci pour la chance, j'en aurai besoin ! Je travaille sur comment utiliser efficacement plusieurs liens dans les réseaux informatiques (par exemple wifi+4G, pas loin de p7 :p )

**Comment by Cocophotos** [comment]
Ok, I look into it.

T'inquiète, c'est souvent long et difficile, mais on arrive tous à terminer :-) Ca m'intéresse de lire ta thèse quand tu l'auras finie. Je m'étais vaguement intéressé au multi-path TCP et au coded TCP, il fut un temps parce que j'avais une configuration Wifi assez particulière chez mes parents.

**Comment by Cocophotos** [comment]
Hi again,

I've implemented the GoTo command for labels / (page)refs, you can check it out by pulling the repo. 

I'm going to change the BibTexParser and finish the GoTo implementation for bib as well. 

Best,

## 

Corentin

**Comment by teto** [comment]
Great ! I tried it here but it fails. I've started debugging it but do you
use a python3 interpreter . My YCM uses python2 .

I tried looking into bibtexparser to add the line but couldn't get past the
code obfuscation I really hope you can :=)

Je travaille essentiellement sur mptcp qui est plutôt prometteur je pense
(dans le sens "amené à être déployé").

2016-09-27 15:48 GMT+02:00 Corentin Ribeyre notifications@github.com:

**Comment by Cocophotos** [comment]
Hi again, 

The code is python 2.7 not python 3.

If you go to a ref (not a citation) and you trigger :YcmCompleter GoTo you jump to the label. 

What do you have when it failed? 

Best

**Comment by teto** [comment]
I have reinstalled youcompleteme so that it runs with python3 (which I use exclusively).
The problem I have in both python2 and 3 is a problem with control characters.

I've played a bit in ipython3 and realized that:

```
import re
r = re.compile("ref\{")
s= " toto \ref{ezae} tes" # does not work
# s= r" toto \ref{ezae} tes" # works
print(r.search(s))
```

would print "None". Because '\r' appears as a control character. Now if you do `s= r" toto \ref{ezae} tes"` it works because the '\r' as interpreted as 2 characters" (as if s = " eaz \ref{toto}". Now raw strings are ok at string instanciation but we can't use that for variables.

I've spent quite some time to find a nice way to escape those and it seems that 

```
import codecs
s = b"my \ref{test} is ok"
s = codecs.escape_encode(line)[0].decode()
```

works fine, i.e., the completer correctly finds the word enclosed in braces.
Problem is then that it can't find a matching label (:YcmDebugInfo shows 0 reference found) because when parsing the file, there seems to be a similar problem.

I've added a logger as it should be done apparently (print >> sys.stdout does not work in python as print became a function):
https://github.com/teto/vim-ycm-latex-semantic-completer/commit/1393fa06764d3c44433005bb9040727113c23c69

I've discovered the :YcmToggleLogs command which is a great help to debug.

**Comment by teto** [comment]
also for the regex, you can get the word straightaway with re.compile("ref{(\W)}")  (you can try on http://pythex.org/)

**Comment by Cocophotos** [comment]
Hi,

Thanks for the debugging. What OS are you running exactly? Could you give me the output of the ":version" command in Vim (so that we know if Vim is compiled against Python3 or Python2), please?

I've updated YCM yesterday to test with ToUnicode and updated all my bundles, and I don't have any of the problems you mentioned above, which puzzle me a lot actually.

For codecs.escape_encode you don't necessary need to have bytes, an unicode string will be OK apparently.

Thanks for the logger, it's a nice touch.

Best,

## 

Corentin

**Comment by teto** [comment]
Sorry I forgot to mention I was using neovim master

```
:version

NVIM
v0.1.6-167-g22dfe69

Build type:
Debug

Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic
-Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla
-fstack-protector-strong -fdiagnostics-color=auto
-DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE
-I/home/teto/neovim/build/config -I/h
ome/teto/neovim/src -I/home/teto/neovim/.deps/usr/include
-I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include
-I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include
-I/home/teto/neovim/.deps/usr/include -I/usr/include -I/home/tet
o/neovim/build/src/nvim/auto
-I/home/teto/neovim/build/include

Compilé par teto@sirius



Optional features included (+) or not (-): +acl   +iconv    +jemalloc
+tui

For differences from Vim, see :help
vim-differences



         fichier vimrc système :
"$VIM/sysinit.vim"

               $VIM par défaut : "/usr/local/share/nvim"
```

Neovim discarded some of the vim encoding stuff so that everything is
considered as utf8. Your vimrc should be compatible with neovim out of the
box, except for the "t_XXX" commands.
I highly recommand it: https://github.com/neovim/neovim

2016-09-27 23:30 GMT+02:00 Corentin Ribeyre notifications@github.com:

**Comment by Cocophotos** [comment]
Hi, 

OK so it may be why we observe such differences. I try your patch with bytes and escaping on my vim and if it works I push the modification to the main repo, then we will be able to implement the bibtex goto. 

I didn't expect such simple commands to raise so many interrogations :) 

Best

**Comment by teto** [comment]
> I didn't expect such simple commands to raise so many interrogations :) 

Me neither but that's the magic of computers :'(
Please note that my patch finds the name of the reference to search for but on neovim at least could not go to it could not fill as the reference db so it won't work as is.
I will test it on vim when I get the time. It's weird that it doesn't on neovim since it should be easier (directly utf8); might be a bug in YCM.

> For codecs.escape_encode you don't necessary need to have bytes, an unicode string will be OK apparently.

cool
