### ISSUE TITLE
Completion does not stop after closing tag

### ISSUE THREAD

**Issue by 0x47** [Cocophotos/vim-ycm-latex-semantic-completer#4]
It seems there is an issue when using both `\ref{` and `\cite{` completion. Here is an illustrative example (`|` indicates the cursor in vim):

```
\ref{|
      label1
      label2
      ...
```

So, the list is shown as expected. Next, I select one entry with tab:

```
\ref{label2|
      label1
      label2     <== this line is highlighted now
      ...
```

I am done choosing the entry and press `}` to close the reference tag. I expect the auto-completion to stop, but instead the menu is shown after the `}`:

```
\ref{label2}|
      label1
      label2
      ...
```

Can you confirm this issue?

EDIT: In fact, I just checked and I can trigger the auto-completion by just re-closing the '\ref{}' or '\cite{}' tags, i.e. removing the `}` and adding a new `}` will trigger the completion and show me all labels. I guess maybe the regular expressions are a not restrictive enough.

**Comment by Cocophotos** [comment]
That's exactly what happened. The program check that ref{ or cite{ appear on the line where the cursor is. It can be fixed by being more restrictive.

If you have a chance, you can try to change that, otherwise I look at it when I have time.

Best,

## 

Corentin

**Comment by 0x47** [comment]
Thanks for you message. I created a small PR to resolve this issue.
