### ISSUE TITLE
Implement LaTeX tag completion

### ISSUE THREAD

**Issue by 0x47** [Cocophotos/vim-ycm-latex-semantic-completer#5]
It would be nice to have a completion for tags such as `\begin{` and `\chapter{` etc. including the proper suggestion after `\begin{`, i.e. `list`, `enumerate`, `equation`, etc. I am not sure whether some kind of completion engine for LaTeX already exists that could be used here (I checked the builtin completers of YCM and they all seem to use/query some already existing library/engine (see, e.g., python completer which uses Jedi). 

If there is no such engine and nobody has worked on this already, I might give it a try and do it from scratch. However, I am not sure if it is wise to basically create a new library to handle all the LaTeX commands (i.e. one has to somehow define what values are possible after a `\begin{`) _by hand_. Maybe there is a more intelligent way to create such a tool. Any ideas?

**Comment by Cocophotos** [comment]
Hi,

It would be nice indeed, but I don't know any library that does that for LaTeX (maybe a simple dictionary lookup is enough for such purpose).

I won't have time to work on that though. If you want to give it a try, don't hesitate.

Thanks a lot,
Best,

Corentin

**Comment by 0x47** [comment]
I will go ahead and implement this. Unfortunately I don't have much spare time either so don't expect much any time soon. However, you can leave this issue open and I will provide updates here.

**Comment by 0x47** [comment]
After giving it some more thought, I'm not going to do this. I realized this is a huge undertaking with little benefit. After all, the identifier completion of YCM does contain all of the tags I use within the file and I rarely use any other tags.

**Comment by Cocophotos** [comment]
Sorry for the late answer, I definitely agree with you.

I'm closing this one, we can always reopen it if we feel the need.

Best
