### ISSUE TITLE
Error in Label Collection

### ISSUE THREAD

**Issue by rabbiveesh** [Cocophotos/vim-ycm-latex-semantic-completer#8]
There's an error in the regex for collecting labels. the code has the pattern to look for as `r".*\label{(.*)}.*"`, which is erroneous, in that it doesn't match the backslash, but rather any lowercase letter followed by `abel{.*}`.

The backslash should be doubled, seeing as in a regex, to match a backslash you double it.

**Comment by Cocophotos** [comment]
You're right. Thanks for pointed it out.

I'll fix that in a minute

Best,

-- 
Corentin
